import { useState, type FormEvent } from 'react';
import { CheckCircle2, ArrowRight } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Link } from '@tanstack/react-router';

const inputClass = 'form-input';
function Field({ label, name, required = false, children }: { label: string; name: string; required?: boolean; children: React.ReactNode }) {
  return <label className="form-field"><span>{label}{required && <span className="required"> *</span>}</span>{children}</label>;
}
export function RequestForm({ mode = 'quote' }: { mode?: 'quote' | 'book' }) {
  const [submitted, setSubmitted] = useState(false);
  const [dateMin] = useState(() => new Date().toISOString().slice(0, 10));
  function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); if (e.currentTarget.reportValidity()) { setSubmitted(true); window.scrollTo({ top: 0, behavior: 'smooth' }); } }
  if (submitted) return <div className="success-state" role="status"><CheckCircle2 size={42} strokeWidth={1.5} /><p className="eyebrow">REQUEST RECEIVED</p><h2>Thanks for reaching out.</h2><p>Your {mode === 'book' ? 'booking' : 'quote'} request has been recorded in this demo. On a live website, the BrightNest team would follow up to confirm the details.</p><Button asChild><Link to="/">Back to Home <ArrowRight /></Link></Button></div>;
  return <form className="request-form" onSubmit={submit}><div className="form-grid"><Field label="Full Name" name="name" required><input className={inputClass} id="name" name="name" autoComplete="name" placeholder="Your full name" required /></Field><Field label="Email Address" name="email" required><input className={inputClass} id="email" name="email" type="email" autoComplete="email" placeholder="you@example.com" required /></Field><Field label="Phone Number" name="phone" required><input className={inputClass} id="phone" name="phone" type="tel" autoComplete="tel" placeholder="(555) 000-0000" required minLength={7} /></Field><Field label="Service Needed" name="service" required><select className={inputClass} id="service" name="service" defaultValue="" required><option value="" disabled>Select a service</option><option>Regular Cleaning</option><option>Deep Cleaning</option><option>Move-In / Move-Out</option><option>Commercial Cleaning</option></select></Field><Field label="Property Type" name="property" required><select className={inputClass} id="property" name="property" defaultValue="" required><option value="" disabled>Select property type</option><option>Apartment</option><option>House</option><option>Office</option><option>Other</option></select></Field><Field label="Preferred Date" name="date" required><input className={inputClass} id="date" name="date" type="date" min={dateMin} required /></Field><Field label="Preferred Time" name="time" required><select className={inputClass} id="time" name="time" defaultValue="" required><option value="" disabled>Select a time</option><option>Morning (8am–12pm)</option><option>Afternoon (12pm–4pm)</option><option>Flexible</option></select></Field><div className="form-field form-empty" aria-hidden="true" /></div><Field label="Anything else we should know?" name="message"><textarea className={inputClass} id="message" name="message" rows={5} placeholder="Tell us a little about your space or any specific requests..." /></Field><div className="form-submit"><Button size="lg" type="submit">{mode === 'book' ? 'Request My Cleaning' : 'Request My Free Quote'} <ArrowRight /></Button><p>No payment required. We’ll confirm availability before anything is booked.</p></div></form>;
}
export function ContactForm() {
  const [submitted, setSubmitted] = useState(false);
  function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); if (e.currentTarget.reportValidity()) setSubmitted(true); }
  if (submitted) return <div className="success-state" role="status"><CheckCircle2 size={40} /><h2>Message received.</h2><p>Thanks for getting in touch. This is a demo, so no message was sent to a business.</p><Button variant="outline" onClick={() => setSubmitted(false)}>Send another message</Button></div>;
  return <form className="request-form contact-form" onSubmit={submit}><div className="form-grid"><Field label="Full Name" name="name" required><input className={inputClass} name="name" autoComplete="name" placeholder="Your full name" required /></Field><Field label="Email Address" name="email" required><input className={inputClass} name="email" type="email" autoComplete="email" placeholder="you@example.com" required /></Field></div><Field label="How can we help?" name="message" required><textarea className={inputClass} name="message" rows={6} placeholder="Tell us what’s on your mind..." required /></Field><Button type="submit" size="lg">Send Message <ArrowRight /></Button></form>;
}
